<?php
$articles = [
    [
        'title' => 'Understanding Furnaces',
        'description' => 'A comprehensive guide to how furnaces work and how to choose the right one for your home.',
        'url' => 'articles/home-heating-with-furnaces.php',
        'image' => 'blogimages/furnace-guide-furnaces.webp',
        'alt_text' => 'Three furnaces displayed side by side in a promotional shot',
        'categories' => ['Furnaces'],
        'date' => '2024-01-29',
        'author' => 'Jacob D',
        'word_count' => 2600,
    ],
    [
        'title' => 'Guide To Air Conditioners',
        'description' => 'Everything you need to know about air conditioners to keep your home cool.',
        'url' => 'articles/guide-to-air-conditioners.php',
        'image' => 'blogimages/guide-to-ac-hero.webp',
        'alt_text' => 'An air conditioning condenser with refrigerant gauges on it.',
        'categories' => ['Air Conditioners'],
        'date' => '2024-02-07',
        'author' => 'Jacob D',
        'word_count' => 2300,
    ],
    [
        'title' => 'Heat Pump Guide',
        'description' => 'Discover the benefits of heat pumps and how they can improve your home\'s efficiency.',
        'url' => 'articles/ultimate-heat-pump-guide.php',
        'image' => 'blogimages/heat-pump-guide-equipment.webp',
        'alt_text' => 'A collection of heat pump equipment',
        'categories' => ['Heat Pumps', 'Air Conditioners'],
        'date' => '2024-02-07',
        'author' => 'Jacob D',
        'word_count' => 2150,
    ],
    [
        'title' => 'Complete Ductless Guide',
        'description' => 'Learn about ductless systems and how they offer flexible heating and cooling solutions.',
        'url' => 'articles/complete-ductless-guide.php',
        'image' => 'blogimages/guide-to-ductless-hero.webp',
        'alt_text' => 'A man and woman are talking in front of a ductless heat pump',
        'categories' => ['Heat Pumps', 'Energy Savings'],
        'date' => '2023-03-06',
        'author' => 'Jacob D',
        'word_count' => 3000,
    ],
    [
        'title' => 'Understanding Thermostats',
        'description' => 'A homeowner\'s guide to choosing and using thermostats effectively.',
        'url' => 'articles/guide-to-thermostats.php',
        'image' => 'blogimages/thermostat-guide-header.webp',
        'alt_text' => 'A hand changes the temperature on a NEST thermostat',
        'categories' => ['Energy Savings','Thermostats'],
        'date' => '2023-03-21',
        'author' => 'Jacob D',
        'word_count' => 2300,
    ],
    [
        'title' => 'Heat Pump VS Air Conditioner 2024 Guide',
        'description' => 'Benefits, disadvantages, and recommendations on your choices for cooling this summer.',
        'url' => 'articles/ac-vs-heat-pump-2024-guide.php',
        'image' => 'blogimages/heat-pump-vs-ac-2024-guide.webp',
        'alt_text' => 'A heat pump and air conditioner are pictured with a versus in between them',
        'categories' => ['Energy Savings', 'Heat Pumps','Air Conditioners'],
        'date' => '2024-04-30',
        'author' => 'Jacob D',
        'word_count' => 2100,
    ],
    [
        'title' => 'Heat Pump Rebates & Tax Credits In 2024',
        'description' => 'Maximize Savings on Heat Pumps with Utility Rebates and Tax Credits',
        'url' => 'articles/heat-pump-rebates-and-tax-credits-2024.php',
        'image' => 'blogimages/heat-pump-tax-credits.webp',
        'alt_text' => 'Money is overlayed over Heat Pump Equipment',
        'categories' => ['Heat Pumps', 'Energy Savings'],
        'date' => '2024-05-15',
        'author' => 'Jacob D',
        'word_count' => 1700,
    ],
    [
        'title' => 'How to Choose the Right Air Conditioner for Your Home',
        'description' => 'A Comprehensive Guide to Cooling Solutions by Bill\'s Heating & A/C',
        'url' => 'articles/how-to-choose-the-right-air-conditioner.php',
        'image' => 'blogimages/guide-to-ac-hero.webp',
        'alt_text' => 'An air conditioning unit with refrigerant guages hanging on it.',
        'categories' => ['Air Conditioners'],
        'date' => '2024-09-26',
        'author' => 'Jacob D',
        'word_count' => 1700,
    ],
    [
        'title' => 'HVAC Definitions',
        'description' => 'A complete glossary of terms related to HVAC',
        'url' => 'articles/hvac-definitions.php',
        'image' => 'images/hvac-definitions-blocks.webp',
        'alt_text' => 'Wood Blocks that spell the word HVAC',
        'categories' => ['Other'],
        'date' => '2024-09-27',
        'author' => 'Jacob D',
        'word_count' => 10200,
    ],
    [
        'title' => 'The Benefits of Regular HVAC Maintenance',
        'description' => 'Why Routine Check-Ups Are Essential for Your Comfort and Savings',
        'url' => 'articles/the-benefits-of-regular-hvac-maintenance.php',
        'image' => 'blogimages/changing-filter.webp',
        'alt_text' => 'A homeowner removes an air filter from a furnace during maintenance',
        'categories' => ['Other', 'Energy Savings'],
        'date' => '2024-09-27',
        'author' => 'Jacob D',
        'word_count' => 1100,
    ],
    [
        'title' => 'Understanding SEER Ratings: What They Mean for Your Energy Bills',
        'description' => 'A Comprehensive Guide by Bill\'s Heating & A/C',
        'url' => 'articles/understanding-seer-ratings.php',
        'image' => 'blogimages/energyguide.webp',
        'alt_text' => 'EnergyGuide label displaying SEER rating on an air conditioner',
        'categories' => ['Energy Savings'],
        'date' => '2024-10-01',
        'author' => 'Jacob D',
        'word_count' => 1000,
    ],
    [
        'title' => 'Top 5 Signs Your Furnace Needs Repair',
        'description' => 'Stay Warm and Safe by Recognizing These Warning Signals',
        'url' => 'articles/top-5-signs-your-furnace-needs-repair.php',
        'image' => 'blogimages/smiling-tech-large.webp',
        'alt_text' => 'A Bills Heating technician works on a gas furnace',
        'categories' => ['Furnaces'],
        'date' => '2024-10-04',
        'author' => 'Jacob D',
        'word_count' => 850,
    ],
    [
        'title' => 'The Advantages of Programmable Thermostats',
        'description' => 'Enhancing Comfort and Efficiency with Bill\'s Heating & A/C',
        'url' => 'articles/advantages-of-programmable-thermostats.php',
        'image' => 'blogimages/thermostat-guide-header.webp',
        'alt_text' => 'Hand adjusting a modern smart thermostat on the wall',
        'categories' => ['Thermostats'],
        'date' => '2024-10-05',
        'author' => 'Jacob D',
        'word_count' => 975,
    ],
    [
        'title' => 'Heat Pumps vs. Traditional HVAC Systems: Which Is Right for You',
        'description' => 'Making the Best Choice with Bill\'s Heating & A/C',
        'url' => 'articles/heat-pumps-vs-traditional-hvac-systems.php',
        'image' => 'blogimages/heat-pump-guide-equipment.webp',
        'alt_text' => 'Various types of York heating and cooling equipment',
        'categories' => ['Heat Pumps'],
        'date' => '2024-10-15',
        'author' => 'Jacob D',
        'word_count' => 1800,
    ],
    [
        'title' => 'Preparing Your HVAC System for Winter',
        'description' => 'Stay Warm with Tips from Bill\'s Heating & A/C',
        'url' => 'articles/preparing-your-hvac-system-for-winter.php',
        'image' => 'blogimages/winter-hvac-preparation.webp',
        'alt_text' => 'Home covered in snow representing winter HVAC preparation',
        'categories' => ['Other'],
        'date' => '2024-10-16',
        'author' => 'Jacob D',
        'word_count' => 475,
    ],
    [
        'title' => 'Energy-Efficient Upgrades to Reduce Your HVAC Costs',
        'description' => 'Discover how energy-efficient upgrades can reduce your HVAC costs.',
        'url' => 'articles/energy-efficient-upgrades-to-reduce-your-hvac-costs.php',
        'image' => 'blogimages/energy-efficient-home.webp',
        'alt_text' => 'People are looking at a chart on their ipad showing energy efficient homeupgrade options',
        'categories' => ['Energy Savings'],
        'date' => '2024-11-15',
        'author' => 'Jacob D',
        'word_count' => 1200,
    ],
    [
        'title' => 'Why Is My Furnace Running but Not Producing Heat?',
        'description' => 'Uncover the Common Causes and Solutions with Bill\'s Heating & A/C',
        'url' => 'articles/why-is-my-furnace-running-but-not-producing-heat.php',
        'image' => 'blogimages/furnace-cutaway.webp',
        'alt_text' => 'Cutaway of a gas furnace with labeled components',
        'categories' => ['Furnaces'],
        'date' => '2024-11-21',
        'author' => 'Jacob D',
        'word_count' => 1000,
    ],
    [
        'title' => 'What Does Freon Smell Like? Understanding Refrigerant Leaks & Safety',
        'description' => 'Learn what Freon smells like and to detect refrigerant leaks.',
        'url' => 'articles/what-does-freon-smell-like.php',
        'image' => 'blogimages/condenser-outside.webp',
        'alt_text' => 'A heat pump condenser pictured outside a home at dusk',
        'categories' => ['Heat Pumps'],
        'date' => '2025-01-13',
        'author' => 'Jacob D',
        'word_count' => 1300,
    ],
    [
        'title' => 'Spring HVAC Maintenance: Key Steps for a Comfortable and Cost-Friendly Season',
        'description' => 'Discover essential tips for spring HVAC maintenance and learn how a little preparation now can save you money and ensure comfort all season long.',
        'url' => 'articles/spring-hvac-maintenance.php',
        'image' => 'blogimages/tech-at-aircon.webp',
        'alt_text' => 'An hvac technician inspects an air conditioner',
        'categories' => ['Energy Savings'],
        'date' => '2025-02-06',
        'author' => 'Jacob D',
        'word_count' => 1000,
    ],
    [
        'title' => 'HVAC Spokane: Year-Round Comfort & Savings with Bill\'s Heating & A/C',
        'description' => 'Learn how Spokane\'s climate affects your heating and cooling needs. Discover the right HVAC solutions for year-round comfort with Bill\'s Heating & A/C.',
        'url' => 'articles/hvac-spokane.php',
        'image' => 'blogimages/hvac-spokane-img.png',
        'alt_text' => 'An image of spokane',
        'categories' => ['Other'],
        'date' => '2025-02-18',
        'author' => 'Jacob D',
        'word_count' => 1250,
    ]
    // Add more articles as needed
];
?>
